"""Parser for LongTR VCFs.

LongTR's VCF schema is described in research-longtr.md §10 and the upstream
README. We only consume the fields we actually need for forensic
cross-checking with the evidence layer:

INFO   : ``MOTIF``, ``PERIOD``, ``BPDIFFS``, ``INEXACT_ALLELE``
FORMAT : ``GT``, ``Q``, ``DP``, ``PDP``, ``ALLREADS``

Everything is parsed into dataclasses with explicit types; downstream code
never touches raw cyvcf2 records.
"""

from __future__ import annotations

from dataclasses import dataclass, field
from pathlib import Path
from typing import Any

from frontstr.errors import CallerError


@dataclass(slots=True, frozen=True)
class LongTRAlleleSpec:
    """One allele (REF or ALT) as reported by LongTR.

    Attributes:
        sequence: The literal nucleotide sequence, or the symbolic ``"<DEL>"``
            for a full deletion of the TR.
        bp_diff: Length difference relative to REF, in bp.  REF is ``0``;
            ``<DEL>`` is ``-len(REF)``.
        inexact: True if the allele was generated by POA consensus
            (``INFO/INEXACT_ALLELE=1``) rather than observed verbatim.
        is_deletion: True iff ``sequence == "<DEL>"``.
    """

    sequence: str
    bp_diff: int
    inexact: bool
    is_deletion: bool


@dataclass(slots=True)
class LongTRSampleCall:
    """Per-sample genotype and read-count fields from one VCF record."""

    sample: str
    gt_indices: tuple[int, ...] | None
    phased: bool
    posterior: float | None
    depth: int
    allreads: dict[int, int] = field(default_factory=dict)
    pdp_hp1: int = 0
    pdp_hp2: int = 0

    def allele_indices_called(self) -> tuple[int, ...]:
        """Return the GT indices excluding ``None``/missing entries."""
        if self.gt_indices is None:
            return ()
        return tuple(i for i in self.gt_indices if i is not None)


@dataclass(slots=True)
class LongTRResult:
    """All information from one VCF record (one locus, one or more samples)."""

    marker_name: str
    chrom: str
    pos: int
    motif: str
    period: str
    alleles: list[LongTRAlleleSpec]
    samples: dict[str, LongTRSampleCall]


def parse_longtr_vcf(vcf_path: Path) -> list[LongTRResult]:
    """Parse a LongTR VCF into per-locus :class:`LongTRResult` objects.

    Args:
        vcf_path: A ``.vcf`` or ``.vcf.gz`` produced by LongTR.

    Returns:
        One :class:`LongTRResult` per record in the VCF, in file order.

    Raises:
        CallerError: If the VCF cannot be opened or parsed.
    """
    if not vcf_path.exists():
        raise CallerError(f"VCF not found: {vcf_path}")
    try:
        import cyvcf2
    except ImportError as exc:
        raise CallerError("cyvcf2 is required to parse LongTR VCFs") from exc

    try:
        vcf = cyvcf2.VCF(str(vcf_path))
    except (OSError, ValueError) as exc:
        raise CallerError(f"Cannot open {vcf_path}: {exc}") from exc

    sample_names: list[str] = list(vcf.samples)
    out: list[LongTRResult] = []
    try:
        for variant in vcf:
            out.append(_parse_record(variant, sample_names))
    except Exception as exc:
        raise CallerError(f"Error parsing {vcf_path}: {exc}") from exc
    finally:
        vcf.close()
    return out


def _parse_record(variant: Any, sample_names: list[str]) -> LongTRResult:
    """Convert one cyvcf2 ``Variant`` into a :class:`LongTRResult`."""
    marker_name = variant.ID or variant.INFO.get("ID") or f"{variant.CHROM}:{variant.POS}"
    motif = _info_str(variant, "MOTIF")
    period = _info_str(variant, "PERIOD")
    bp_diffs = _info_int_list(variant, "BPDIFFS")
    inexact_flags = _info_int_list(variant, "INEXACT_ALLELE")

    alleles: list[LongTRAlleleSpec] = [
        LongTRAlleleSpec(sequence=variant.REF, bp_diff=0, inexact=False, is_deletion=False)
    ]
    alt_list = list(variant.ALT) if variant.ALT else []
    for i, alt in enumerate(alt_list):
        is_del = alt == "<DEL>"
        bp = bp_diffs[i] if i < len(bp_diffs) else (-len(variant.REF) if is_del else 0)
        inx = bool(inexact_flags[i]) if i < len(inexact_flags) else False
        alleles.append(
            LongTRAlleleSpec(
                sequence="<DEL>" if is_del else alt,
                bp_diff=bp,
                inexact=inx,
                is_deletion=is_del,
            )
        )

    samples: dict[str, LongTRSampleCall] = {}
    for j, name in enumerate(sample_names):
        samples[name] = _parse_sample(variant, j, name)

    return LongTRResult(
        marker_name=str(marker_name),
        chrom=str(variant.CHROM),
        pos=int(variant.POS),
        motif=motif,
        period=period,
        alleles=alleles,
        samples=samples,
    )


def _parse_sample(variant: Any, j: int, name: str) -> LongTRSampleCall:
    """Extract FORMAT fields for sample index ``j``."""
    gt_indices, phased = _parse_genotype(variant, j)
    posterior = _format_float(variant, "Q", j)
    depth = _format_int(variant, "DP", j) or 0
    allreads = _parse_allreads(_format_str(variant, "ALLREADS", j))
    pdp_hp1, pdp_hp2 = _parse_pdp(_format_str(variant, "PDP", j))
    return LongTRSampleCall(
        sample=name,
        gt_indices=gt_indices,
        phased=phased,
        posterior=posterior,
        depth=depth,
        allreads=allreads,
        pdp_hp1=pdp_hp1,
        pdp_hp2=pdp_hp2,
    )


# ---------------------------------------------------------------------------
# Low-level field accessors
# ---------------------------------------------------------------------------


def _info_str(variant: Any, key: str) -> str:
    value = variant.INFO.get(key)
    if value is None:
        return ""
    if isinstance(value, bytes):
        return value.decode("ascii", errors="replace")
    return str(value)


def _info_int_list(variant: Any, key: str) -> list[int]:
    value = variant.INFO.get(key)
    if value is None:
        return []
    if isinstance(value, int):
        return [value]
    if isinstance(value, (str, bytes)):
        raw = value.decode() if isinstance(value, bytes) else value
        return [int(x) for x in raw.split(",") if x not in ("", ".")]
    try:
        return [int(x) for x in value]
    except (TypeError, ValueError):
        return []


def _parse_genotype(variant: Any, j: int) -> tuple[tuple[int, ...] | None, bool]:
    """Return ``(indices, phased)`` for sample ``j``.

    Missing genotypes (``./.``) return ``(None, False)``. Indices that are
    individually missing are reported as the special value ``-1``.
    """
    try:
        gt = variant.genotypes[j]
    except (AttributeError, IndexError, TypeError):
        return None, False
    if gt is None:
        return None, False
    *alleles, phased = gt
    if not alleles or all(a is None or a < 0 for a in alleles):
        return None, bool(phased)
    return tuple(int(a) if a is not None else -1 for a in alleles), bool(phased)


def _format_float(variant: Any, key: str, j: int) -> float | None:
    val = _format_cell(variant, key, j)
    if val is None:
        return None
    try:
        f = float(val)
    except (TypeError, ValueError):
        return None
    if f != f:  # NaN sentinel used by cyvcf2 for missing
        return None
    return f


_INT32_MIN = -(2**31)


def _format_int(variant: Any, key: str, j: int) -> int | None:
    val = _format_cell(variant, key, j)
    if val is None:
        return None
    try:
        i = int(val)
    except (TypeError, ValueError):
        return None
    if i == _INT32_MIN:  # cyvcf2 sentinel for missing
        return None
    return i


def _format_str(variant: Any, key: str, j: int) -> str:
    val = _format_cell(variant, key, j)
    if val in (None, ".", ""):
        return ""
    if isinstance(val, bytes):
        val = val.decode("ascii", errors="replace")
    return str(val)


def _format_cell(variant: Any, key: str, j: int) -> Any:
    """Return the scalar value at sample ``j`` for FORMAT ``key``.

    cyvcf2 returns Number=1 numeric fields as a 2D ``ndarray`` of shape
    ``(n_samples, 1)``; string fields come back as a 1D array of shape
    ``(n_samples,)``. We collapse both to a Python scalar.
    """
    arr = _format_raw(variant, key)
    if arr is None or j >= len(arr):
        return None
    cell = arr[j]
    if hasattr(cell, "__len__") and not isinstance(cell, (str, bytes)):
        if len(cell) == 0:
            return None
        cell = cell[0]
    return cell


def _format_raw(variant: Any, key: str) -> Any:
    try:
        return variant.format(key)
    except (KeyError, ValueError):
        return None


def _parse_allreads(s: str) -> dict[int, int]:
    """LongTR ALLREADS: ``"0|45;-3|2;6|18"`` → ``{0: 45, -3: 2, 6: 18}``."""
    if not s:
        return {}
    out: dict[int, int] = {}
    for tok in s.split(";"):
        if "|" not in tok:
            continue
        bp_raw, n_raw = tok.split("|", 1)
        try:
            out[int(bp_raw)] = int(n_raw)
        except ValueError:
            continue
    return out


def _parse_pdp(s: str) -> tuple[int, int]:
    """LongTR PDP: ``"12|28"`` → ``(12, 28)``. Empty/missing → ``(0, 0)``."""
    if not s or "|" not in s:
        return (0, 0)
    a_raw, b_raw = s.split("|", 1)
    try:
        return int(a_raw), int(b_raw)
    except ValueError:
        return (0, 0)
